// Dados mock dos dispositivos - você pode substituir por dados reais da sua API
export const deviceConfigurations = {
  "1": {
    id: "1",
    name: "PC-ADMIN-01",
    type: "Desktop",
    status: "online" as const,
    location: "Sala de TI",
    processor: "Intel Core i7-12700K",
    memory: "32GB DDR4",
    storage: "1TB NVMe SSD",
    network: "Gigabit Ethernet",
    display: '27" 4K Monitor',
    os: "Windows 11 Pro",
    lastUpdate: "15/01/2024 14:30",
    ipAddress: "192.168.1.100",
  },
  "2": {
    id: "2",
    name: "LAPTOP-DEV-02",
    type: "Laptop",
    status: "online" as const,
    location: "Desenvolvimento",
    processor: "AMD Ryzen 7 5800H",
    memory: "16GB DDR4",
    storage: "512GB NVMe SSD",
    network: "Wi-Fi 6 + Bluetooth 5.2",
    display: '15.6" Full HD IPS',
    battery: "85% - 4h restantes",
    os: "Ubuntu 22.04 LTS",
    lastUpdate: "14/01/2024 09:15",
    ipAddress: "192.168.1.105",
  },
  "3": {
    id: "3",
    name: "SERVER-DB-01",
    type: "Servidor",
    status: "maintenance" as const,
    location: "Data Center",
    processor: "Intel Xeon E5-2690 v4",
    memory: "128GB DDR4 ECC",
    storage: "4TB RAID 10 SSD",
    network: "10Gb Ethernet",
    os: "CentOS 8",
    lastUpdate: "13/01/2024 22:00",
    ipAddress: "192.168.1.50",
  },
  "4": {
    id: "4",
    name: "PHONE-ADMIN",
    type: "Smartphone",
    status: "offline" as const,
    location: "Administração",
    processor: "Snapdragon 888",
    memory: "8GB LPDDR5",
    storage: "256GB UFS 3.1",
    network: "5G + Wi-Fi 6",
    display: '6.7" AMOLED 120Hz',
    battery: "Desconectado",
    os: "Android 13",
    lastUpdate: "12/01/2024 18:45",
    ipAddress: "192.168.1.120",
  },
  // Adicione mais dispositivos conforme necessário
}

export type DeviceConfig = (typeof deviceConfigurations)[keyof typeof deviceConfigurations]
